### ISSUE TITLE
输出长度是否可控

### ISSUE THREAD

**Issue by pilipala818** [lxchtan/PoNet#2]
感谢诸位的工作并将其开源，

我在modelscope上运行该模型，发现部分文本返回空且该情况与输入文本长度无关。

请问该模型的输出长度是否可控？

谢谢。

**Comment by lxchtan** [comment]
感谢你对我们工作的关注。抱歉回复的有点晚。

请问你是在尝试哪个任务呢？以及使用的是哪一个checkpoint呢？能否提供更详细的运行信息以及出错样例？
