### ISSUE TITLE
可以用来做生成任务吗

### ISSUE THREAD

**Issue by wangwang110** [lxchtan/PoNet#3]
感谢开源！
请问ponet可以被用来做长文本的生成式摘要吗？论文中的任务好像都是将ponte当作编码器，decoder部分的参数会开放吗？

**Comment by lxchtan** [comment]
谢谢你对我们工作的关注。
出于长文本多在encoder部分出现的考虑，我们目前仅将ponet作为编码器。
如果需要用作生成式的任务，并且需要生成的句子不是很长的话，最简单的方式是应用encoder-decoder架构，将encoder替换为ponet，decoder用full-attention的结构。
