### ISSUE TITLE
这个模型支持的文本最大长度有限制吗

### ISSUE THREAD

**Issue by TomShenTom** [lxchtan/PoNet#4]

**Comment by lxchtan** [comment]
谢谢你对我们工作的关注。
我们在预训练的时候将句子长度截断到512。对于需要更长句子支持的长文本下游任务，我们把文本最大长度设置成了4096，具体来说我们将position embeddings进行循环复制，请参考run_long_classification.py以及run_shell/3-LongTask.sh。这个最大长度可以设置为更大的值。
